# version: "3.8"

services:
  app:
    # image: dflourusso/hikvision2mqtt:1.0.1
    build: .
    ports:
      - "${PORT}:3000" # Maps container port dynamically from .env
      - "5060:5060/udp"
    environment:
      # - PORT=${PORT} # Pass PORT from .env to container
      - MQTT_URL=${H2M_MQTT_URL}
      - MQTT_USERNAME=${H2M_MQTT_USERNAME}
      - MQTT_PASSWORD=${H2M_MQTT_PASSWORD}
      - MQTT_PUBLISH_TOPIC=${H2M_MQTT_PUBLISH_TOPIC}
      - API_TOKEN=${H2M_API_TOKEN}
      - INCLUDE_ORIGINAL_DATA=${H2M_INCLUDE_ORIGINAL_DATA}
      - ONLY_KNOWN_EVENTS=${H2M_ONLY_KNOWN_EVENTS}
    env_file:
      - .env
    restart: always # Ensure it restarts on failure
